const indNames=['RSI','GD','CCI','MACD','Momentum','Pivot','Volumen','Trend'];
let stocks=[...window.baseStocks,...JSON.parse(localStorage.getItem('extraStocks')||'[]')].map((x,i)=>({...x,price:null,chg:null,history:[],inds:makeIndicators(x.s,i)}));
let depotData=JSON.parse(localStorage.getItem('depotData')||'{}');
function makeIndicators(sym,i){let h=[...sym].reduce((a,c)=>a+c.charCodeAt(0),0)+i*7;return indNames.reduce((o,k,j)=>(o[k]=((h+j*11)%17===0)||((h+j*5)%23===0),o),{});} 
function seed(sym){return [...sym].reduce((a,c)=>a+c.charCodeAt(0),0)}
function defaultBuyPrice(st){return Math.max(1,((seed(st.s)%450)+20)*(0.82+((seed(st.s)%35)/100)))}
function holding(st){if(!st.d)return null;if(!depotData[st.s]) depotData[st.s]={shares:1,buyPrice:defaultBuyPrice(st)};return depotData[st.s]}
function saveDepot(){localStorage.setItem('depotData',JSON.stringify(depotData))}
function gain(st){let h=holding(st),p=st.price;if(!h||!p||!h.buyPrice)return null;let total=(p-h.buyPrice)*(h.shares||1);let pct=((p-h.buyPrice)/h.buyPrice)*100;return {total,pct}}
function sell(st){return Object.values(st.inds).some(Boolean)}
function route(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active'); if(id==='depot') renderDepot(); if(id==='signals') renderSignals(); scrollTo(0,0)}
document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));
function groups(){return [...new Set(stocks.map(s=>s.g))].sort()}
function initFilters(){groupFilter.innerHTML='<option value="">Alle Gruppen</option>'+groups().map(g=>`<option>${g}</option>`).join('')}
function renderHome(){let q=search.value.toLowerCase(),gf=groupFilter.value;let list=stocks.filter(s=>(!gf||s.g===gf)&&(`${s.s} ${s.n}`.toLowerCase().includes(q)));stockGrid.innerHTML=list.map(card).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>showDetail(c.dataset.s));kpiStocks.textContent=`${stocks.length} Aktien`;kpiSell.textContent=`${stocks.filter(sell).length} Verkauf`;kpiDepot.textContent=`${stocks.filter(s=>s.d).length} Depot`}
function card(st){let depotBadge=st.d?'<span class="depotmark">Im Depot</span>':'';return `<div class="card ${st.d?'inDepot':''}" data-s="${st.s}"><div class="row"><span class="symbol">${st.s}</span><span>${depotBadge}<span class="badge">${st.g}</span></span></div><h3>${st.n}</h3><div class="price">${fmt(st.price)}</div><div class="row"><span class="${(st.chg??0)>=0?'ok':'bad'}">${st.chg==null?'Kurs lädt…':(st.chg>0?'+':'')+st.chg.toFixed(2)+'%'}</span><strong class="${sell(st)?'bad':'ok'}">${sell(st)?'Verkaufssignal':'OK'}</strong></div><div class="indicators">${indNames.slice(0,6).map(k=>`<span class="ind ${st.inds[k]?'on':''}">${k}</span>`).join('')}</div></div>`}
function fmt(p){return p==null?'—':p.toLocaleString('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:2})}
function fmtMoney(v){return v==null?'—':v.toLocaleString('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:2})}
function chartSvg(st){let h=st.history&&st.history.length?st.history:makeFallbackHistory(st);let w=760,hgt=280,padL=62,padR=18,padT=18,padB=48;let min=Math.min(...h.map(x=>x.p)),max=Math.max(...h.map(x=>x.p));if(max===min){max+=1;min-=1}let x=i=>padL+i*(w-padL-padR)/(h.length-1);let y=p=>padT+(max-p)*(hgt-padT-padB)/(max-min);let pts=h.map((d,i)=>`${x(i).toFixed(1)},${y(d.p).toFixed(1)}`).join(' ');let ticks=[0,Math.floor((h.length-1)/2),h.length-1].map(i=>`<text x="${x(i)}" y="${hgt-16}" text-anchor="middle">${h[i].d}</text>`).join('');let yt=[min,(min+max)/2,max].map(v=>`<g><line x1="${padL-5}" x2="${w-padR}" y1="${y(v)}" y2="${y(v)}"/><text x="${padL-10}" y="${y(v)+4}" text-anchor="end">${v.toFixed(0)}</text></g>`).join('');return `<div class="chartWrap"><h3>Chartverlauf</h3><svg viewBox="0 0 ${w} ${hgt}" role="img" aria-label="Chartverlauf mit beschrifteter Zeitachse"><g class="gridline">${yt}</g><line class="axis" x1="${padL}" y1="${hgt-padB}" x2="${w-padR}" y2="${hgt-padB}"/><line class="axis" x1="${padL}" y1="${padT}" x2="${padL}" y2="${hgt-padB}"/><polyline class="chartLine" points="${pts}"/><text class="axisLabel" x="${(w+padL-padR)/2}" y="${hgt-4}" text-anchor="middle">Zeitachse</text><text class="axisLabel" transform="translate(16 ${(hgt-padB+padT)/2}) rotate(-90)" text-anchor="middle">Kurs</text>${ticks}</svg></div>`}
function makeFallbackHistory(st){let base=st.price||((seed(st.s)%450)+20);let arr=[];for(let i=0;i<24;i++){let p=base*(0.9+i/120+Math.sin((i+seed(st.s)%8)/2.5)*0.04);arr.push({d:i===0?'6M':i===12?'3M':i===23?'Heute':'',p})}return arr}
function showDetail(sym){let st=stocks.find(x=>x.s===sym),g=gain(st);detailContent.innerHTML=`<div class="panel"><div class="detailbox"><div><span class="symbol">${st.s}</span><h2>${st.n}</h2><p class="badge">${st.g}${st.d?' · Im Depot':''}</p><p class="big">${fmt(st.price)}</p><p class="${(st.chg??0)>=0?'ok':'bad'}">${st.chg==null?'Keine Live-Daten verfügbar':(st.chg>0?'+':'')+st.chg.toFixed(2)+'%'}</p>${st.d?`<p>Gewinn/Verlust seit Kauf: <strong class="${g&&g.total>=0?'ok':'bad'}">${g?fmtMoney(g.total)+' / '+g.pct.toFixed(2)+'%':'—'}</strong></p>`:''}<h3 class="${sell(st)?'bad':'ok'}">${sell(st)?'Verkaufssignal aktiv':'Kein Verkaufssignal'}</h3><p class="muted">Logik: Sobald mindestens ein Indikator negativ anschlägt, wird ein Verkaufssignal eingeblendet.</p></div><div><h3>Detailanalyse</h3><table><tbody>${indNames.map(k=>`<tr><td>${k}</td><td class="${st.inds[k]?'bad':'ok'}">${st.inds[k]?'negativ / prüfen':'neutral / positiv'}</td></tr>`).join('')}</tbody></table></div></div>${chartSvg(st)}</div>`;route('detail')}
function renderDepot(){let list=stocks.filter(s=>s.d);depotTable.innerHTML=table(list,true);saveDepot()}
function renderSignals(){let list=stocks.filter(sell);signalTable.innerHTML=table(list,false)}
function table(list,depot){return `<table><thead><tr><th>Kennung</th><th>Aktie</th><th>Gruppe</th><th>Kurs</th>${depot?'<th>Kaufkurs</th><th>Gewinn/Verlust</th>':''}<th>Trendindikatoren</th><th>Signal</th></tr></thead><tbody>${list.map(s=>{let h=holding(s),g=gain(s);return `<tr onclick="showDetail('${s.s}')"><td class="symbol">${s.s}</td><td>${s.n}${depot?' · Depot':''}</td><td>${s.g}</td><td>${fmt(s.price)}</td>${depot?`<td>${fmt(h.buyPrice)}</td><td class="${g&&g.total>=0?'ok':'bad'}">${g?fmtMoney(g.total)+' / '+g.pct.toFixed(2)+'%':'—'}</td>`:''}<td>${Object.entries(s.inds).filter(x=>x[1]).map(x=>x[0]).join(', ')||'—'}</td><td class="${sell(s)?'bad':'ok'}">${sell(s)?'Verkauf':'OK'}</td></tr>`}).join('')}</tbody></table>`}
async function loadPrices(){await Promise.all(stocks.slice(0,120).map(async st=>{try{let u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(st.s)}?range=6mo&interval=1wk`;let r=await fetch(u);let j=await r.json();let res=j.chart.result[0];let closes=res.indicators.quote[0].close;let times=res.timestamp;let pairs=closes.map((p,i)=>p?{p,d:new Date(times[i]*1000).toLocaleDateString('de-DE',{month:'2-digit',year:'2-digit'})}:null).filter(Boolean);st.history=pairs;let p=pairs.at(-1).p,old=pairs.at(-2)?.p||p;st.price=p;st.chg=((p-old)/old)*100}catch(e){let base=(seed(st.s)%450)+20;st.price=base;st.chg=((seed(st.s)%80)-40)/10;st.history=makeFallbackHistory(st)}}));renderHome();if(document.getElementById('depot').classList.contains('active'))renderDepot()}
search.oninput=renderHome;groupFilter.onchange=renderHome;addStock.onclick=()=>{let s=newSymbol.value.trim().toUpperCase(),n=newName.value.trim()||s,g=newGroup.value;if(!s)return;let extra=JSON.parse(localStorage.getItem('extraStocks')||'[]');extra.push({s,n,g,d:false});localStorage.setItem('extraStocks',JSON.stringify(extra));stocks.push({s,n,g,d:false,price:null,chg:null,history:[],inds:makeIndicators(s,stocks.length)});newSymbol.value='';newName.value='';initFilters();renderHome();loadPrices()};
initFilters();renderHome();loadPrices();
