const DATA=window.AKTIEN_DATA||{stocks:[]};
const $=s=>document.querySelector(s); const fmt=n=>n==null?'–':Number(n).toLocaleString('de-DE',{maximumFractionDigits:2});
const pct=n=>n==null?'–':(Number(n)*100).toLocaleString('de-DE',{maximumFractionDigits:2})+' %';
const depotKey='aktientool_v33_depot'; let depot=JSON.parse(localStorage.getItem(depotKey)||'{}');
function saveDepot(){localStorage.setItem(depotKey,JSON.stringify(depot)); renderAll();}
function isDepot(s){return depot[s.symbol]?.active || Number(s.numbersDepot)>0}
function signalClass(v){return Number(v)>0?'good':Number(v)<0?'bad':''}
function sellCount(s){let n=Number(s.sell||0); const sig=s.signals||{}; Object.keys(sig).forEach(k=>{if(k.includes('-')&&Number(sig[k])>0)n++}); return n}
function buyCount(s){let n=Number(s.buy||0); const sig=s.signals||{}; Object.keys(sig).forEach(k=>{if(k.includes('+')&&Number(sig[k])>0)n++}); return n}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active')); $('#'+id).classList.add('active'); document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('activeBtn',b.dataset.page===id)); window.scrollTo(0,0)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page)); $('#backBtn').onclick=()=>showPage('overview');
function initFilters(){let groups=[...new Set(DATA.stocks.map(s=>s.group).filter(Boolean))].sort(); $('#groupFilter').innerHTML='<option value="">Alle Gruppen</option>'+groups.map(g=>`<option>${g}</option>`).join(''); $('#search').oninput=renderOverview; $('#groupFilter').onchange=renderOverview;}
function renderOverview(){const q=$('#search').value.toLowerCase(), g=$('#groupFilter').value; const body=$('#stockTable tbody'); let rows=DATA.stocks.filter(s=>(!g||s.group===g)&&((s.symbol+s.name+s.group).toLowerCase().includes(q))); body.innerHTML=rows.map(s=>`<tr class="${isDepot(s)?'inDepot':''}" onclick="detail('${s.symbol}')"><td>${isDepot(s)?'📌':''}</td><td><b>${s.symbol}</b></td><td>${s.name}</td><td>${s.group}</td><td>${fmt(s.price)}</td><td class="${signalClass(s.percent)}">${pct(s.percent)}</td><td class="good">${buyCount(s)||''}</td><td class="bad">${sellCount(s)||''}</td><td class="${signalClass(s.trendScore)}">${fmt(s.trendScore)}</td><td>${s.volumeFlag||''}</td></tr>`).join('');}
function renderStats(){let st=DATA.stocks; $('#version').textContent=DATA.version; $('#countAll').textContent=st.length; $('#countBuy').textContent=st.filter(buyCount).length; $('#countSell').textContent=st.filter(sellCount).length; $('#countDepot').textContent=st.filter(isDepot).length;}
function card(s){return `<div class="card ${isDepot(s)?'inDepot':''}"><h3>${s.name} <span class="muted">${s.symbol}</span></h3><div class="grid"><div class="metric">Kurs<br><b>${fmt(s.price)}</b></div><div class="metric">Änderung<br><b class="${signalClass(s.percent)}">${pct(s.percent)}</b></div><div class="metric">Kauf<br><b class="good">${buyCount(s)}</b></div><div class="metric">Verkauf<br><b class="bad">${sellCount(s)}</b></div><div class="metric">Trend<br><b>${fmt(s.trendScore)}</b></div><div class="metric">Vol+<br><b>${s.volumeFlag||'–'}</b></div></div><div class="actions"><button onclick="detail('${s.symbol}')">Detailanalyse</button><button onclick="toggleDepot('${s.symbol}')">${isDepot(s)?'Depot entfernen':'Ins Depot'}</button></div></div>`}
function renderLists(){ $('#buyList').innerHTML=DATA.stocks.filter(buyCount).sort((a,b)=>buyCount(b)-buyCount(a)).map(card).join('')||'<p class="muted">Keine Kaufsignale.</p>'; $('#sellList').innerHTML=DATA.stocks.filter(sellCount).sort((a,b)=>sellCount(b)-sellCount(a)).map(card).join('')||'<p class="muted">Keine Verkaufssignale.</p>'; renderDepot();}
function toggleDepot(sym){depot[sym]=depot[sym]||{}; depot[sym].active=!depot[sym].active; saveDepot();}
function renderDepot(){let arr=DATA.stocks.filter(isDepot); $('#depotList').innerHTML=arr.map(s=>{let d=depot[s.symbol]||{}; let kk=Number(d.buyPrice||s.depotSheet?.Kaufkurs||0), pcs=Number(d.qty||s.depotSheet?.Stck||0); let gl=kk&&pcs&&s.price?(s.price-kk)*pcs:null; return `<div class="card"><h3>${s.name} <span class="muted">${s.symbol}</span></h3><div class="grid"><div class="metric">Kurs<br><b>${fmt(s.price)}</b></div><div class="metric">Gewinn/Verlust seit Kauf<br><b class="${signalClass(gl)}">${gl==null?'–':fmt(gl)+' €'}</b></div><div class="metric">Verkaufssignal<br><b class="bad">${sellCount(s)}</b></div><div class="metric">Kaufsignal<br><b class="good">${buyCount(s)}</b></div><div class="metric">Trendindikator<br><b>${fmt(s.trendScore)}</b></div><div class="metric">Volumen<br><b>${s.volumeFlag||'–'}</b></div></div><div class="depotInputs"><input type="number" step="0.01" placeholder="Kaufkurs" value="${d.buyPrice||''}" onchange="setDepot('${s.symbol}','buyPrice',this.value)"><input type="number" step="1" placeholder="Stück" value="${d.qty||''}" onchange="setDepot('${s.symbol}','qty',this.value)"></div><div class="actions"><button onclick="detail('${s.symbol}')">Detailanalyse</button><button onclick="toggleDepot('${s.symbol}')">Depot entfernen</button></div></div>`}).join('')||'<p class="muted">Noch keine Aktien im Depot markiert.</p>';}
function setDepot(sym,k,v){depot[sym]=depot[sym]||{active:true}; depot[sym][k]=v; depot[sym].active=true; saveDepot();}
function detail(sym){let s=DATA.stocks.find(x=>x.symbol===sym); if(!s)return; const sig=s.signals||{}, tr=s.trend||{}; $('#detailContent').innerHTML=`<h2>${s.name} <span class="muted">${s.symbol}</span></h2><canvas id="chart" width="900" height="320"></canvas><div class="grid"><div class="metric">Kurs<br><b>${fmt(s.price)}</b></div><div class="metric">Kauf gesamt<br><b class="good">${buyCount(s)}</b></div><div class="metric">Verkauf gesamt<br><b class="bad">${sellCount(s)}</b></div><div class="metric">Trend<br><b>${fmt(s.trendScore)}</b></div><div class="metric">52W Hoch<br><b>${fmt(tr['52Wo Hoch'])}</b></div><div class="metric">52W Tief<br><b>${fmt(tr['52Wo Tief'])}</b></div></div><h3>Indikatoren</h3><div class="grid">${Object.keys(sig).filter(k=>!['Kennung','Aktie'].includes(k)).map(k=>`<div class="metric">${k}<br><b class="${k.includes('-')?'bad':'good'}">${fmt(sig[k])}</b></div>`).join('')}</div><div class="actions"><button onclick="toggleDepot('${s.symbol}')">${isDepot(s)?'Depot entfernen':'Ins Depot'}</button></div>`; showPage('detail'); drawChart(s.history||[]);}
function drawChart(points){const c=$('#chart'),ctx=c.getContext('2d'),w=c.width,h=c.height,pad=46; ctx.clearRect(0,0,w,h); if(!points.length){ctx.fillText('Keine Kursdaten',pad,40);return} const ys=points.map(p=>p.y).filter(Number.isFinite), min=Math.min(...ys), max=Math.max(...ys), span=max-min||1; ctx.strokeStyle='#334155'; ctx.lineWidth=1; ctx.beginPath(); ctx.moveTo(pad,pad); ctx.lineTo(pad,h-pad); ctx.lineTo(w-pad,h-pad); ctx.stroke(); ctx.fillStyle='#94a3b8'; ctx.font='12px system-ui'; for(let i=0;i<=5;i++){let y=h-pad-i*(h-2*pad)/5, val=min+i*span/5; ctx.fillText(fmt(val),6,y+4); ctx.strokeStyle='#1f2937'; ctx.beginPath(); ctx.moveTo(pad,y); ctx.lineTo(w-pad,y); ctx.stroke();} let xFor=i=>pad+i*(w-2*pad)/(points.length-1); let yFor=v=>h-pad-(v-min)*(h-2*pad)/span; ctx.strokeStyle='#38bdf8'; ctx.lineWidth=2; ctx.beginPath(); points.forEach((p,i)=>{let x=xFor(i), y=yFor(p.y); i?ctx.lineTo(x,y):ctx.moveTo(x,y)}); ctx.stroke(); ctx.fillStyle='#cbd5e1'; [0,Math.floor(points.length/2),points.length-1].forEach(i=>{let label=points[i].x===0?'heute':points[i].x+' T'; ctx.fillText(label,xFor(i)-15,h-18)}); ctx.fillText('Zeitachse: Handelstage bis heute',w/2-80,h-4);}
function renderAll(){renderStats(); renderOverview(); renderLists();}
initFilters(); renderAll();
